name: PR

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 600000

      - name: Type check
        run: yarn tsc

      - name: Lint
        run: yarn lint:all

      - name: Build backend
        run: yarn build:backend
